In [ ]:
# 激活函数：根据数值和阈值关系，筛选结果；
# 激活函数是非线性函数，如果是线性，则不需要多层
# 决定神经元是否激活，控制信息传递；在反向传播中，影响梯度下降速度
# 常见的激活函数有：Sigmoid, ReLU

In [ ]:
# 神经网络层与层之间采用矩阵的运算表示

In [3]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[1,1]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [4]:
C = A*B
print(C)

[[1 2]
 [3 4]]


In [5]:
D = np.dot(A, B)
print(D)

[[3 3]
 [7 7]]
